### ISSUE TITLE
hw1 zad3  Ujemny przyrost confirmed cases

### ISSUE THREAD

**Issue by Wincioor11** [korona-science/homework-Wincioor11#1]
Dla niektórych krajów w niektórych dniach przyrost jest ujemny, tak więc testy jednostkowe, które sprawdzają czy cases_da1 != cases_day2 są błędne, lub to data set jest błędny.

Wg mnie powinno się sprawdzać różnicę o patrzeć czy jest większa od 0. Tak też zrobiłem, ale wasze dwa test casy sprawdzały w tych przypadkach warunek nierówności nie zwracając uwagi na to czy przybyło czy jakims cudem ubyło danego dnia. 

Ps. Ostatecznie ofc dostosowałem się do waszego warunku, ale mnie serce bolało jak zmieniałem xd

Pozdro chłopaki!

**Comment by RouNNdeL** [comment]
Tak jak napisałem w komentarzu pod commitem, w momencie pisania testów pod uwagę brałem oba warunki `>` oraz `!=` i zwracały te same wartości. Ale dzięki za Issue, następnym razem oznacz mnie
